/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Game.java
 *
 * Created on 10/10/2011, 07:19:06 PM
 */
package GUI;

import java.awt.Graphics;
import Juego.Juego;
import Puntaje.IngresarPuntaje;
import Tiempo.*;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.image.BufferStrategy;
import Puntaje.Puntaje;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Samuel Beracasa
 */
public class Game extends javax.swing.JFrame implements KeyListener {

    /** Creates new form Game */
    public Game() {
        initComponents();
        createBufferStrategy(2);
        juego.setHeroe(this.getWidth(), this.getHeight());
        juego.setEnemigos();
    }

    @Override
    public void paint(Graphics g) {
        juego.acutaliza(this);
        if(juego.getEstado()==juego.modo.gameover){
            IngresarPuntaje p;
            String args[]=null;
            try {
                p = new IngresarPuntaje();
                p.setPuntaje(juego.getPuntaje());
                p.main(args);
            } catch (IOException ex) {
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.setVisible(false);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Juego juego = new Juego();
    Tiempo pruebaTiempo = new Tiempo();

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws InterruptedException {
        Game ventana = new Game();
        ventana.setVisible(true);
        ventana.addKeyListener(ventana);
        ventana.setBounds(220, 10, 600, 750);

        while (true) {
            Thread.sleep(30);
            ventana.repaint();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    public void keyTyped(KeyEvent e) {
    }

    public void keyPressed(KeyEvent e) {
        try {
            juego.accion(e.getKeyCode());
        } catch (IOException ex) {
            Logger.getLogger(Game.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Game.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void keyReleased(KeyEvent e) {
        juego.reaccion(e.getKeyCode());
    }
}
